1. What is a Python library? Why do we use Python libraries?

In [ ]:
'''
A Python library is a collection of pre-written code that provides functionalities
to solve specific problems or tasks. We use Python libraries to save time, leverage
specialized functionalities, improve code efficiency, benefit from community support,
focus on problem-solving, and facilitate interoperability with other technologies.
'''

2. What is the difference between Numpy array and List?

In [ ]:
'''
Numpy arrays are specialized for numerical data and provide more efficient storage
and operations compared to Python lists, which are more general-purpose and flexible
but less efficient for numerical computations. The choice between numpy arrays and lists
depends on the specific requirements of your application, especially if you are dealing
with large amounts of numerical data or require efficient numerical operations.
'''

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np


arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr.shape)
print(arr.size)

(3, 4)
12


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr[2, 3]


12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

flattened_arr = arr.flatten()

odd_index_elements = [flattened_arr[i] for i in range(len(flattened_arr)) if i % 2 == 1]

print(odd_index_elements)

[2, 4, 6, 8, 10, 12]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [8]:
import numpy as np

random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.83335525 0.98553529 0.09785192]
 [0.98704105 0.88950768 0.48828031]
 [0.4731241  0.82102834 0.33171691]]


8. Describe the difference between np.random.rand and np.random.randn?

In [10]:
import numpy as np

random_matrix = np.random.rand(3, 3)
normal_matrix = np.random.randn(3, 3)

print(random_matrix)
print()
print(normal_matrix)

'''
np.random.rand:

- Uniform distribution
- Values in the range [0, 1)
- Used for generating normalized or bounded random values np.random.randn:

np.random.randn:

- Standard normal distribution
- Values centered around 0 with a standard deviation of 1
- Used for generating data that follows a normal distribution

'''

[[0.37358627 0.38799266 0.41295144]
 [0.95870749 0.00350918 0.61450549]
 [0.09213567 0.81443237 0.66307907]]

[[-0.6057707  -0.13476677 -1.43586453]
 [ 0.11953403  2.62927807  1.0449363 ]
 [-0.07387395 -0.95026063 -0.75909934]]


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [11]:
import numpy as np

#Defining the numpy array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

#Increasing dimension by adding a new axis at position 0
expanded_array = np.expand_dims(array, axis=0)

#Printing results
print("Original array:")
print(array)
print("Shape of original array:", array.shape)

print("\nExpanded array:")
print(expanded_array)
print("Shape of expanded array:", expanded_array.shape)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of original array: (3, 4)

Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape of expanded array: (1, 3, 4)


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

#Transposing the array
transposed_array = np.transpose(array)

print("Original array:")
print(array)
print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python :

1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [14]:
import numpy as np

#Defining matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

#1. Index-wise multiplication
index_wise_multiply = A * B

#2. Matrix multiplication
matrix_multiply = A @ B.T

#3. Add both matrices
matrix_addition = A + B

#4. Subtract matrix B from A
matrix_subtraction = A - B

#5. Divide Matrix B by A (element-wise division)
matrix_division = np.divide(B, A)

#Printing results
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

print("\n1. Index-wise multiplication:")
print(index_wise_multiply)

print("\n2. Matrix multiplication (A @ B.T):")
print(matrix_multiply)

print("\n3. Matrix addition (A + B):")
print(matrix_addition)

print("\n4. Matrix subtraction (A - B):")
print(matrix_subtraction)

print("\n5. Matrix division (B / A):")
print(matrix_division)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1. Index-wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix multiplication (A @ B.T):
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix addition (A + B):
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix subtraction (A - B):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Matrix division (B / A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be use^ to swap the byte or^er of an array?

In [1]:
import numpy as np

#Creating an array with a specific byte order
arr = np.array([1, 256, 65536], dtype=np.int32)

print("Original array:", arr)

swapped_arr = arr.byteswap()

print("Array with swapped byte order:", swapped_arr)

Original array: [    1   256 65536]
Array with swapped byte order: [16777216    65536      256]


13.What is the significance of the np.linalg.inv function?

In [3]:
'''
'np.linalg.inv' function is primarily used to calculate the inverse of a square matrix.

In regression analysis, the normal equation method to find the coefficient vector \(\beta\) is given by:
\[ \beta = (X^TX)^{-1}X^Ty \]
where \(X\) is the design matrix and \(y\) is the response vector.

'''

import numpy as np

A = np.array([[1, 2], [3, 4]])

#Computing the inverse of the matrix using np.linalg.inv
A_inv = np.linalg.inv(A)

print("Original Matrix A:")
print(A)
print()

print("Inverse of Matrix A:")
print(A_inv)
print()

#Verifying the result by multiplying A with its inverse
I = np.dot(A, A_inv)

print("Product of A and its inverse (Identity Matrix):")
print(I)


Original Matrix A:
[[1 2]
 [3 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Product of A and its inverse (Identity Matrix):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


14. What does the np.reshape function do, and how is it used?

In [4]:
'''
The np.reshape function in NumPy is used to change the shape of an array without
changing its data. It provides a new view of the original array with a different
shape, specified by the user. This function is very useful when you need to
manipulate the dimensions of an array to fit a specific requirement for further
computations or data processing.

'''

import numpy as np

#Creatin a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

#Reshaping it to array of 2x3
reshaped_arr = np.reshape(arr, (2, 3))

print("Original array:")
print(arr)

print("Reshaped array (2x3):")
print(reshaped_arr)


Original array:
[1 2 3 4 5 6]
Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

In [6]:
'''
Broadcasting in NumPy is a powerful mechanism that allows operations on arrays of
different shapes in a way that makes sense in the context of the operation.
It automatically expands the dimensions of smaller arrays so that they have the
same shape as larger arrays during arithmetic operations, without making copies
of the data. This allows for more efficient and concise code.
'''


import numpy as np

#Defining a 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Define a 1D array
arr_1d = np.array([1, 2, 3])

# Add the 1D array to the 3D array
result = arr_3d + arr_1d

print("3D array:\n", arr_3d)
print()
print("1D array:", arr_1d)
print()
print("Result of broadcasting addition:\n", result)


3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1D array: [1 2 3]

Result of broadcasting addition:
 [[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]
